### ISSUE TITLE
Missing output

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#1]
Hi,

Just trying this out on NetBSD and wondering about the missing outputs.
Disclaimer: I didn't look through the code, just comparing it to `macchina`:

![2024-03-23-214810_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/96ec974e-26a7-468f-961c-4997a5cd8d0d)

**Comment by charklie** [comment]
can you run these commands and show me what they output?
`cat /etc/hostname` 
`cat /etc/lsb-release`
`uptime -p`
`echo $XDG_CURRENT_DEKSTOP`

tbh if you pull and rebuild it might get fixed as ive changed alot of the code

could you try running it in bash instead of elvish? it could be a problem with elvish having different syntax

**Comment by 0323pin** [comment]
> can you run these commands and show me what they output?
> `cat /etc/hostname`

No such file or directory. This does not exist on NetBSD, on the other hand there's a `hostname` command.
```
~> hostname
mybox
```

> `cat /etc/lsb-release`

This doesn't exist either.
```
~> uname -s
NetBSD
```

> `uptime -p`
uptime: unknown option -- p

```
~> uptime
 3:41PM  up 11 mins, 1 user, load averages: 0.52, 0.63, 0.38
```

> `echo $XDG_CURRENT_DEKSTOP` 

This could actually be related to me using `elvish` as my default shell but, it's just because I'm using a plain window manager. `macchina` actually uses `wmctrl` to fetch the WM.

> tbh if you pull and rebuild it might get fixed as ive changed alot of the code

Yes, it's a lot better :)

> could you try running it in bash instead of elvish?

![2024-03-24-153920_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/277f02f7-d596-4526-aa0d-411434b02f93)

**Comment by charklie** [comment]
alright, im gonna do some switching up with the commands and it should be fixed in a couple hours
thank you so much for reporting this!

**Comment by 0323pin** [comment]
@charklie Thanks!

In the meantime, I've pushed a package to the work-in-progress repository, https://mail-index.netbsd.org/pkgsrc-wip-changes/2024/03/24/msg029890.html

**Comment by charklie** [comment]
Thank you so much! This is actually my first tool so its great to see it getting some love.

All the previous issues should be fixed by now, else you could give me a DM on discord, my username is chborli.

**Comment by 0323pin** [comment]
Thanks for caring and adding support for NetBSD.

> you could give me a DM on discord, my username is chborli.

I don't use discord but, if you are on Matrix, that's a possibility, @0323pin:converser.eu

0.2.3 solves most of the issues and l might move the package into the main branch.
It's only the memory readout which, is still missing/wrong:

![2024-03-25-082027_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/1df7894b-be0b-4ef4-81a9-e2abeee3eba2)

_Distro_ is fine, as it makes no sense for BSD.

**Comment by 0323pin** [comment]
0.2.4 solves the memory issue :tada:  but, now I'm missing the window manager

![2024-03-25-144534_955x519_scrot](https://github.com/charklie/rsftch/assets/90570748/5172b862-5efa-4844-ac60-37fb40490623)
