### ISSUE TITLE
zero packages

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#6]
🤔 I don't think I have zero packages installed

![2024-04-12-081013_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/7e9e6a01-b743-4839-bddb-3d0c3285eb71)

🤣 

Also, you seem to have forgotten to release 0.4.3 to crates.io

Regards

**Comment by charklie** [comment]
> 🤔 I don't think I have zero packages installed
> 
> 
> 
> ![2024-04-12-081013_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/7e9e6a01-b743-4839-bddb-3d0c3285eb71)
> 
> 
> 
> 🤣 
> 
> 
> 
> Also, you seem to have forgotten to release 0.4.3 to crates.io
> 
> 
> 
> Regards
@0323pin 

What's the command to list every single package installed on netbsd? That'll fix the issue
I'll wait to push 0.4.3 until this is fixed.

**Comment by 0323pin** [comment]
> What's the command to list every single package installed on netbsd? That'll fix the issue
I'll wait to push 0.4.3 until this is fixed.

```
~> pkg_info | wc -l
     183
~> pkgin list | wc -l
     183
~> ls pkgdb/ | wc -l
     184
```

It's also possible to use what's already defined in `libmacchina`, https://github.com/Macchina-CLI/libmacchina/blob/c357e97fa799962c90b7edb87af8923d03b5410e/src/netbsd/mod.rs#L416

If you use the count on the pkgdb directory you need to do "-1", as it includes the database itself.

**Comment by 0323pin** [comment]
Btw, https://github.com/beucismis/awesome-fetch/pull/61 😄

**Comment by charklie** [comment]
> Btw, https://github.com/beucismis/awesome-fetch/pull/61 😄

Thank you!
I just pushed 0.4.3-2 onto crates.io and packages _should_ be fixed. 
If it works, you can close the issue.

**Comment by charklie** [comment]
And I remember you putting that windows support is coming in the pkgsrc description for rsftch, would it be possible to remove that? Adding windows support would be such a large task that I don't think I will ever have the energy to do.

**Comment by 0323pin** [comment]
> And I remember you putting that windows support is coming in the pkgsrc description for rsftch, would it be possible to remove that? Adding windows support would be such a large task that I don't think I will ever have the energy to do.

Yes, I'll fix that!

**Comment by charklie** [comment]
> Yes, I'll fix that!

Thank you!

**Comment by 0323pin** [comment]
![2024-04-12-125741_864x503_scrot](https://github.com/charklie/rsftch/assets/90570748/8084959f-6d79-4572-b2ac-ebee09ed8627)

Something still wrong

**Comment by charklie** [comment]
Could you clone the repo, and inside fns.rs at around line 64 below `let installed_managers = get_package_managers();
`
add this line: `println!("{:?}", get_package_managers());`

**Comment by charklie** [comment]
> Could you clone the repo, and inside fns.rs at around line 64 below `let installed_managers = get_package_managers(); ` add this line: `println!("{:?}", get_package_managers());`

then run `cargo r` and screenshot the output

**Comment by 0323pin** [comment]
Sure,

![2024-04-12-125741_864x503_scrot](https://github.com/charklie/rsftch/assets/90570748/cd125b14-5048-40b3-9880-7ab4f1c158f2)

**Comment by 0323pin** [comment]
![2024-04-12-130558_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/706c2606-684f-42f3-892a-4f2726a73138)

**Comment by charklie** [comment]
So that means that its not finding any package managers, does `pkgin --version` not work?

**Comment by charklie** [comment]
I gotta fix that icon too, as this is how its meant to be:
![image](https://github.com/charklie/rsftch/assets/157241212/430af4b7-89de-42fa-84bb-26be32e37798)

**Comment by 0323pin** [comment]
> does `pkgin --version` not work?

```
~> pkgin --v
pkgin: unknown option -- -
Usage: pkgin [-46cdfhlnPtvVy] command [package ...]

Commands and shortcuts:
list                (ls  ) - List installed local packages
avail               (av  ) - List all available remote packages
search              (se  ) - Search for a remote package
install             (in  ) - Install or upgrade packages
update              (up  ) - Refresh local and remote package lists
upgrade             (ug  ) - Upgrade all packages
full-upgrade        (fug ) - Upgrade all packages (deprecated)
remove              (rm  ) - Remove packages and any dependent packages
keep                (ke  ) - Mark packages that should be kept
unkeep              (uk  ) - Mark packages that can be autoremoved
export              (ex  ) - Display PKGPATH for all keep packages
import              (im  ) - Import keep package list from file
show-keep           (sk  ) - Display keep packages
show-no-keep        (snk ) - Display autoremovable packages
autoremove          (ar  ) - Remove orphaned dependencies
clean               (cl  ) - Remove downloaded package files
show-deps           (sd  ) - List remote package direct dependencies
show-full-deps      (sfd ) - List remote package full dependencies
show-rev-deps       (srd ) - List local package reverse dependencies
provides            (prov) - Show which shared libraries a package provides
requires            (req ) - Show which shared libraries a package requires
show-category       (sc  ) - List all packages belonging to a category
show-pkg-category   (spc ) - Show categories a package belongs to
show-all-categories (sac ) - List all known categories
pkg-content         (pc  ) - Show remote package content
pkg-descr           (pd  ) - Show remote package long-description
pkg-build-defs      (pbd ) - Show remote package build definitions
stats               (st  ) - Show local and remote package statistics
```

**Comment by charklie** [comment]
But `--version` doesn't?

**Comment by 0323pin** [comment]
> But `--version` doesn't?

It's the same,
```
~> pkgin --version
pkgin: unknown option -- -
Usage: pkgin [-46cdfhlnPtvVy] command [package ...]

Commands and shortcuts:
list                (ls  ) - List installed local packages
avail               (av  ) - List all available remote packages
search              (se  ) - Search for a remote package
install             (in  ) - Install or upgrade packages
update              (up  ) - Refresh local and remote package lists
upgrade             (ug  ) - Upgrade all packages
full-upgrade        (fug ) - Upgrade all packages (deprecated)
remove              (rm  ) - Remove packages and any dependent packages
keep                (ke  ) - Mark packages that should be kept
unkeep              (uk  ) - Mark packages that can be autoremoved
export              (ex  ) - Display PKGPATH for all keep packages
import              (im  ) - Import keep package list from file
show-keep           (sk  ) - Display keep packages
show-no-keep        (snk ) - Display autoremovable packages
autoremove          (ar  ) - Remove orphaned dependencies
clean               (cl  ) - Remove downloaded package files
show-deps           (sd  ) - List remote package direct dependencies
show-full-deps      (sfd ) - List remote package full dependencies
show-rev-deps       (srd ) - List local package reverse dependencies
provides            (prov) - Show which shared libraries a package provides
requires            (req ) - Show which shared libraries a package requires
show-category       (sc  ) - List all packages belonging to a category
show-pkg-category   (spc ) - Show categories a package belongs to
show-all-categories (sac ) - List all known categories
pkg-content         (pc  ) - Show remote package content
pkg-descr           (pd  ) - Show remote package long-description
pkg-build-defs      (pbd ) - Show remote package build definitions
stats               (st  ) - Show local and remote package statistics
Exception: pkgin exited with 1
```

**Comment by charklie** [comment]
Ah, then I'll just switch to `ls pkgdb/ | wc -l`, where is "pkgdb" located? in root?

**Comment by 0323pin** [comment]
> Ah, then I'll just switch to `ls pkgdb/ | wc -l`, where is "pkgdb" located? in root?

`/usr/pkg/pkgdb`
![2024-04-12-131321_955x531_scrot](https://github.com/charklie/rsftch/assets/90570748/ecf8105c-44d0-4d75-98f5-63e14abb9cf8)

**Comment by charklie** [comment]
Is there any package-related command that does have the `--version` flag?

**Comment by 0323pin** [comment]
> Is there any package-related command that does have the `--version` flag?

`pkg_info` does but, it's `-V`

```
~> pkg_info -V
20210410
```

Does it help?

**Comment by 0323pin** [comment]
Also, it's better to use `pkg_info`, as not every user has `pkgin`

**Comment by charklie** [comment]
And pkg_info does also not have `--version`?

**Comment by 0323pin** [comment]
> And pkg_info does also not have `--version`?

Nope, the flag is `-V`

from `man pkg_info`,

```
[...]
     -u      Show information for all user-installed packages: automatically
             installed packages (as dependencies of other packages) are not
             displayed.  See also -a.

     -V      Print version number and exit.

     -v      Turn on verbose output.

     -X      Print summary information for each package.  The summary format
             is described in pkg_summary(5).  Its primary use is to contain
             all information about the contents of a (remote) binary package
             repository needed by package managing software.
[...]
```

```
~> pkg_info --version
pkg_info: unknown option -- -
usage: pkg_info [-BbcDdFfhIikLmNnpqRrSsVvX] [-E pkg-name] [-e pkg-name]
                [-K pkg_dbdir] [-l prefix] pkg-name ...
       pkg_info [-a | -u] [flags]
       pkg_info [-Q variable] pkg-name ...
Exception: pkg_info exited with 1
```

**Comment by charklie** [comment]
Alright, I'll switch some things around and it should be fixed in ca 15 minutes.

**Comment by 0323pin** [comment]
> Alright, I'll switch some things around and it should be fixed in ca 15 minutes.

😥 Sorry about that.

**Comment by charklie** [comment]
> 😥 Sorry about that.

No worries, not your fault (well kinda as you're a pkgsrc maintainer :joy:)

**Comment by charklie** [comment]
@0323pin 

`pkg` command doesn't exist on NetBSD, right?

**Comment by charklie** [comment]
(should) be fixed now.

**Comment by 0323pin** [comment]
> @0323pin
> 
> `pkg` command doesn't exist on NetBSD, right?

correct
![2024-04-12-133359_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/287e92cf-89dd-4b56-a16e-0a1df9008baa)

**Comment by charklie** [comment]
> (should) be fixed now.

Did it work?

**Comment by 0323pin** [comment]
> (should) be fixed now.

yes ...

![2024-04-12-133739_1338x734_scrot](https://github.com/charklie/rsftch/assets/90570748/295d483c-9a3b-4025-b73d-02b839bf72b0)

Thanks

**Comment by charklie** [comment]
Great! Ill change the icon because some funky buisiness happened with it.

**Comment by 0323pin** [comment]
Let me know when 0.4.4 is on crates.io and I'll fix the update.

**Comment by charklie** [comment]
> Let me know when 0.4.4 is on crates.io and I'll fix the update.

Should be up now.

**Comment by 0323pin** [comment]
![2024-04-12-135037_778x469_scrot](https://github.com/charklie/rsftch/assets/90570748/b9d06383-2c92-4ab9-a26a-efdab5c2dd07)

[Merged](http://mail-index.netbsd.org/pkgsrc-changes/2024/04/12/msg296900.html) with the updated package description.
